### ISSUE TITLE
DKBans crashing TyphoonLimbo

### ISSUE THREAD

**Issue by RikoDEV** [DevKrieger/DKBans#11]
**Version**
2.2.2

**Platform**
BungeeCord

**Minecraft server Version**
1.14.4

**Minecraft client Version**
1.14.4

**Describe the bug**
I am using the TyphoonLimbo server as my login lobby. After the player joins the bungeecord with the DKBans plugin running, the authorization server is crashing.

Error log
```
2019/07/20 10:58:16 #4 -> 0 &{498 ********0.136c913f8516f7633f89ccb21c4cdc7fa7d[{"name":"textures","value":"eyJ0aW1lc3RhbXAiOjE1NjM2MjAyOTYwMDMsInByb2ZpbGVJZCI6ImViMTdiMGQ0MDM4YzQ3NDk5YTIzZDVkM2RmMzVmYjU5IiwicHJvZmlsZU5hbWUiOiJSaWtvREVWIiwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzkzOWNjZjc2NDE3ODQwYTgxYTg2MzNmMzQ0MDc4ZTExMzRmYjBlNjA5NTA5ZTAyYzg0NGJkNjVhNzI2YjMwY2MifX19","signature":"gKY864PtrldgUNHwlO+wuIou9UESDZqUTcEiHwcJh5mHI/xuS/M9zCVPdqzfdSx9kX6pynJJQk8jN9nqT/LALBZoH71w5f2o5Pa9KcoVzwO24zdNtkp2vwzHwdVvhdnOzNyrCjp2VZBDYEnyo4dUf92R8K8nPVmCxNxrRCfcCs5Vo594+ad7sCT+HtR3j8Zd1cvWcCGvX0LqeGP2f2JG0Cl7NRDMoNPkc09mFYdJVYCM4Sua9VEQ1VrJh3/TkqPoLlFcE8ip6ntAleP3feRr5HHsdXSyh0RFifdVGJEK892upesBftuuxOPpmz+JOGfEYnEdB7xeOI9MBX9DkSL5T1tTlMd2u+iv2mQlSZrwEHK5Yb0dFL7goN5lfaaMSfed6hWk+URxAxRqrHySnBl1BroVLXnSnpeYTPARKkJ+sDE/svEmGLxkID2VXNBJyiRwaYp7DMjOKuFW9QV7wso5v5vXhS48NQvWdSh5koS0PHMMaOc6faT8RMHauwAuItm322S/W+ruPdJWALVvXeSU9riAaDgkLNuoL8vgZM1lfEy4qAcH5li+oUsQQDsXDopRJIvuhLrMXPW3Zy1gKG7TmlEfWPpAOIXXhkf2JIFEQH50l8XY2vGGf24RQ2ALwIUCqvMu5Cd63zbZ6a3wW3yJynCpraS/6opWpVazMEJGNYA\u003d"}] 3000 2}
2019/07/20 10:58:16 #4 -> 0 &{RikoDEV}
2019/07/20 10:58:16 #4 <- 2 &{d979912c-bb24-4f23-a6ac-c32985a1e5d3 RikoDEV}
2019/07/20 10:58:16 #4 <- 37 &{0 3 1 2 255 default false}
2019/07/20 10:58:16 #4 <- 53 &{0 0 0 0 0 0 0}
2019/07/20 10:58:16 #4 <- 17 &{[{0 false [] -1 <nil>}] 0}
2019/07/20 10:58:16 #4 <- 14 &{{
"text": "You are in the limbo",
"color": "dark_red"
} 0}
2019/07/20 10:58:16 #4 <- 12 &{8354dc03-c25b-4d11-8aed-9599641afa16 0 {
"text": "You are in the limbo",
"color": "dark_red"
} 1 2 0 0}
2019/07/20 10:58:16 #4 <- 83 &{0xc000446650 <nil>}
2019/07/20 10:58:16 #4 -> 9 &{minecraft:register [108 101 103 97 99 121 58 102 109 108 0 108 101 103 97 99 121 58 102 109 108 124 104 115 0 100 107 98 97 110 115 58 100 107 98 97 110 115 0 108 101 103 97 99 121 58 102 111 114 103 101 0 98 117 110 103 101 101 99 111 114 100 58 109 97 105 110 0 100 98 97 58 118 101 114 105 102 121 0 98 116 108 112 58 98 114 105 100 103 101 0]}
2019/07/20 10:58:16 #4 -> 9 &{dkbans:dkbans [0 113 123 34 117 117 105 100 34 58 34 99 57 49 51 102 56 53 49 45 54 102 55 54 45 51 51 102 56 45 57 99 99 98 45 50 49 99 52 99 100 99 55 102 97 55 100 34 44 34 99 97 117 115 101 34 58 34 76 79 71 73 78 34 44 34 112 114 111 112 101 114 116 105 101 115 34 58 123 34 100 97 116 97 115 34 58 123 125 125 44 34 97 99 116 105 111 110 34 58 34 117 112 100 97 116 101 80 108 97 121 101 114 34 125 0]}
2019/07/20 10:58:16 #4 -> 9 &{btlp:bridge [0 48 75 217 209 0 0 0 5 0 0 0 5 0 6 50 46 56 46 49 49 0]}
2019/07/20 10:58:16 4 -> Unknown packet #4
2019/07/20 10:58:16 #4 -> 9 &{minecraft:brand [7 118 97 110 105 108 108 97 0]}
2019/07/20 10:58:16 RikoDEV is using vanilla client
2019/07/20 10:58:16 #4 <- 24 &{minecraft:brand [13 116 121 112 104 111 111 110 108 105 109 98 111 0]}
2019/07/20 10:58:16 4 -> Unknown packet #0
2019/07/20 10:58:16 4 -> Unknown packet #14
2019/07/20 10:58:16 #4 -> 9 &{btlp:bridge [0 48 75 217 209 0 0 0 5 0 0 0 5 0 6 50 46 56 46 49 49 0]}
2019/07/20 10:58:16 #4 -> 9 &{dkbans:dkbans [0 144 123 34 112 108 97 121 101 114 115 34 58 91 123 34 117 117 105 100 34 58 34 99 57 49 51 102 56 53 49 45 54 102 55 54 45 51 51 102 56 45 57 99 99 98 45 50 49 99 52 99 100 99 55 102 97 55 100 34 44 34 110 97 109 101 34 58 34 82 105 107 111 68 69 86 34 44 34 115 101 114 118 101 114 34 58 34 108 111 98 98 121 34 44 34 112 114 111 120 121 34 58 34 80 114 111 120 121 45 49 34 125 93 44 34 97 99 116 105 111 110 34 58 34 117 112 100 97 116 101 79 110 108 105 110 101 80 108 97 121 101 114 115 34 125 128]}
panic: runtime error: makeslice: len out of range
goroutine 51 [running]:
github.com/TyphoonMC/TyphoonCore.(*Player).ReadByteArray(...)
/root/go/src/github.com/TyphoonMC/TyphoonCore/utils.go:267
github.com/TyphoonMC/TyphoonCore.(*PacketPlayPluginMessage).Read(0xc0004293e0, 0xc0001f2080, 0x1, 0x63c360, 0xc0004293e0)
/root/go/src/github.com/TyphoonMC/TyphoonCore/packet_handle.go:549 +0x135
github.com/TyphoonMC/TyphoonCore.(*Player).HandlePacket(0xc0001f2080, 0x9, 0x1, 0xc0001e5768, 0x1, 0x0, 0x0)
/root/go/src/github.com/TyphoonMC/TyphoonCore/packet_registry.go:64 +0x324
github.com/TyphoonMC/TyphoonCore.(*Player).ReadPacketWithoutCompression(0xc0001f2080, 0x63c360, 0xc0004292c0, 0x0, 0x0)
/root/go/src/github.com/TyphoonMC/TyphoonCore/connection.go:224 +0xed
github.com/TyphoonMC/TyphoonCore.(*Player).ReadPacket(0xc0001f2080, 0x63c360, 0xc0004292c0, 0x0, 0x0)
/root/go/src/github.com/TyphoonMC/TyphoonCore/connection.go:204 +0x70
github.com/TyphoonMC/TyphoonCore.(*Core).handleConnection(0xc0000ec000, 0x63d260, 0xc000010028, 0x4)
/root/go/src/github.com/TyphoonMC/TyphoonCore/typhoon.go:118 +0x321
created by github.com/TyphoonMC/TyphoonCore.(*Core).Start
/root/go/src/github.com/TyphoonMC/TyphoonCore/typhoon.go:57 +0x23b
```

**To Reproduce**
How do we reproduce this bug?
The way tho trigger this bug.

1. Create bungeecord proxy with TyphoonLimbo as hub.
2. Join bungeecord proxy with DKBans running.
3. TyphoonLimbo crash.

**Comment by DevKrieger** [comment]
DKBans sends on every player login to each sub server a sync message. I think your server does not support the „PluginMessageChannel“ packet or the server has a problem with this packet (Try contacting the developer of this runtime).

If it is not possible to fix, I can offer to create an option for disabling the network synchronisation.

Best regards
Dkrieger

**Comment by RikoDEV** [comment]
So option to disable it in config would be a good solution.

**Comment by DevKrieger** [comment]
I added a option for disabling network synchronization.

DKBans version **2.2.3**
