### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by todworgen** [DevKrieger/DKBans#2]
**Version**
2.0.8

**Platform**
On which platform is DKBans running? (example: BungeeCord)

**Minecraft server Version**
1.13 Bungeecord and Spigot

**Minecraft client Version**
1.13

**Describe the bug**
Cant join via Bungeecord:

Getting only the errormessage:
This was on Bungeecord console:
 disconnected with: Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.server.v1_13_R1.ResourceKeyInvalidException: Non [a-z0-9_.-] character in namespace of location: DKBans:DKBans

This on Spigot:

[01:52:44 ERROR]: Couldn't register custom payload
java.lang.IllegalArgumentException: Channel must be entirely lowercase
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:478) ~[1.13.jar:git-Spigot-fe3ab0d-162bda9]
        at org.bukkit.craftbukkit.v1_13_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:1246) ~[1.13.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2434) ~[1.13.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.PacketPlayInCustomPayload.a(SourceFile:45) ~[1.13.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.PacketPlayInCustomPayload.a(SourceFile:9) ~[1.13.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[1.13.jar:git-Spigot-fe3ab0d-162bda9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [1.13.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [1.13.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [1.13.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [1.13.jar:git-Spigot-fe3ab0d-162bda9]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [1.13.jar:git-Spigot-fe3ab0d-162bda9]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[01:52:44 INFO]: YukiHai lost connection: Invalid payload REGISTER!

**To Reproduce**

Just installed the plugin and followed the installation steps on the wiki

**Comment by DevKrieger** [comment]
Should be fixed in the newest version (2.0.9).

Thanks for reporting.

**Comment by JHarris12345** [comment]
Not fixed
