### ISSUE TITLE
Bug report on Chat

### ISSUE THREAD

**Issue by AggroMC** [DevKrieger/DKBans#8]
Neuste Plugin Version, Neueste Bungeecord Version. Immer wenn ich etwas schreibe kommt Illegal characters in chat und dieser fehler:

[29.05.2019 18:53:09] INFO: [Proxy-1] 18:52:42 [WARNING] Error dispatching event ChatEvent(super=TargetedEvent(sender=TeamAggro, receiver=net.md_5.bungee.ServerConnection@3e898e8d), cancelled=false, message=/tempban) to listener ch.dkrieger.bansystem.bungeecord.listener.PlayerListener@497c1d78
[29.05.2019 18:53:09] INFO: [Proxy-1] java.lang.NullPointerException
[29.05.2019 18:53:09] INFO: [Proxy-1]     at ch.dkrieger.bansystem.bungeecord.listener.PlayerListener.onChat(PlayerListener.java:180)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at java.lang.reflect.Method.invoke(Method.java:498)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:397)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:142)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
[29.05.2019 18:53:09] INFO: [Proxy-1]     at java.lang.Thread.run(Thread.java:748)
[29.05.2019 18:53:09] INFO: [Proxy-1] >
root@Master $

HILFE!!!

**Comment by DevKrieger** [comment]
Ich kann nicht genau sagen woran der Fehler liegt. Ich gehe davon aus, dass es sich um eine Message handelt die falsch geladen wurde.

Bitte halten Sie sich in Zukunft an die Vorlage, Danke.

**Comment by AggroMC** [comment]
Ok. Der Startfehler ist das: :26:20 [INFO] [DKBans] plugin is starting
19:26:20 [INFO] [DKBans] BanSystem 2.1.9 by Davide Wietlisbach
19:26:20 [INFO] [DKBans] Could not load config file.
19:26:20 [INFO] [DKBans] Error: java.nio.charset.MalformedInputException: Input length = 1
19:26:20 [WARNING] Error enabling plugin DKBans
java.lang.NullPointerException
	at ch.dkrieger.bansystem.lib.config.SimpleConfig.addValue(SimpleConfig.java:85)
	at ch.dkrieger.bansystem.lib.config.SimpleConfig.addAndGetMessageValue(SimpleConfig.java:134)
	at ch.dkrieger.bansystem.lib.config.MessageConfig.onLoad(MessageConfig.java:35)
	at ch.dkrieger.bansystem.lib.config.SimpleConfig.loadConfig(SimpleConfig.java:59)
	at ch.dkrieger.bansystem.lib.BanSystem.systemBootstrap(BanSystem.java:97)
	at ch.dkrieger.bansystem.lib.BanSystem.<init>(BanSystem.java:88)
	at ch.dkrieger.bansystem.bungeecord.BungeeCordBanSystemBootstrap.onLoad(BungeeCordBanSystemBootstrap.java:68)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:329)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:232)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:265)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by AggroMC** [comment]
Was ist da Falsch!!?!?! bitte hilfe

**Comment by DevKrieger** [comment]
Der Fehler wir in der Nähe beim Prefix liegen, ich empfehle die message Config zu löschen und neu zu generieren.
